on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service: 'tripletex'
            package: 'tripletex-export-server'
            dockerfile: 'Dockerfile.generic-node-app'
          - service: 'fiken'
            package: 'fiken-export-server'
            dockerfile: 'Dockerfile.generic-node-app'
          - service: 'auth'
            package: 'folio-authorization-service'
            dockerfile: 'Dockerfile.generic-node-app'
          - service: 'slack-logger'
            package: 'folio-slack-logger'
            dockerfile: 'Dockerfile.generic-node-app'
    steps:
    - name: start deployment
      uses: bobheadxi/deployments@v0.4.3
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: prod/${{ matrix.service }}
        desc: master-a293047

    - name: do my deploy
      run: echo 'I DID SOMETHING COOL!'

    - name: update deployment status
      uses: bobheadxi/deployments@v0.4.3
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}