name: Testing

on:
  pull_request:
    
jobs:
  deployment:
    name: Test (${{ matrix.world }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        world: [hello, there, you]
    env:
      TAG: ${GITHUB_REF#refs/*/}-$(git rev-parse --short HEAD)
    steps:
      - name: Set tag
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/*/}-$(git rev-parse --short ${{ github.sha }})"
      - uses: LouisBrunner/checks-action@v1.1.1
        with:
          name: ${{ matrix.world }}:${{ steps.tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          conclusion: ${{ job.status }}
          output: |
            {
              "summary": "Tagged build with ${{ steps.tag.outputs.tag }}"
            }
