on:
  release:
    types: [published, edited]
jobs:
  tag-major:
    name: Push major-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        with:
          publish_latest_tag: true
